# ===== Tailscale =====
tailscale_authkey: "tskey-REEMPLAZA-ESTO"   # mejor: vault
tailscale_hostname_prefix: "k3s"
tailscale_tags: "tag:k3s"

# Opciones útiles:
tailscale_accept_dns: "true"     # habilitar DNS de Tailscale (MagicDNS)
tailscale_ssh: "true"           # Tailscale SSH (ya está en true)

# ===== k3s =====
k3s_version: "v1.34.3+k3s1"     # versión estable más reciente (Kubernetes 1.34.3)
k3s_disable_traefik: true
k3s_disable_servicelb: true

# ===== Cilium =====
cilium_version: "1.18.5"        # versión estable más reciente del chart
cilium_chart_repo: "https://helm.cilium.io/"
cilium_chart_name: "cilium"
cilium_namespace: "kube-system"