# Title: K3s Version
# Description: K3s version to install.
# Type: str
# Required: false
k3s_version: "v1.35.0+k3s1"
# Title: Containerd Optimized
# Description: Enable containerd optimized configuration.
# Type: bool
# Required: false
k3s_common_containerd_optimized: true
# Title: Containerd Default Runtime
# Description: Default container runtime to use.
# Type: str
# Required: false
k3s_common_containerd_default_runtime: "runc"
# Title: Containerd Additional Runtimes
# Description: List of additional container runtimes to register.
# Type: list
# Required: false
k3s_common_containerd_additional_runtimes: []
# Title: Containerd Sandbox Image
# Description: Pause container image for the CRI sandbox.
# Type: str
# Required: false
k3s_common_containerd_sandbox_image: "registry.k8s.io/pause:3.10.1"
# Title: K3s CNI Binary Directory
# Description: Path to CNI binaries.
# Type: str
# Required: false
k3s_cni_bin_dir: "/opt/cni/bin"
# Title: K3s CNI Configuration Directory
# Description: Path to CNI configuration files.
# Type: str
# Required: false
k3s_cni_conf_dir: "/etc/cni/net.d"
# Title: Recreate K3s
# Description: If true, uninstalls and wipes previous K3s installation before deploying.
# Type: bool
# Required: false
k3s_recreate: false
# Title: Restart Handler Name
# Description: Handler name for restarting k3s (differs between server and agent).
# Type: str
# Required: false
k3s_common_restart_handler: "Restart k3s"
