---
galaxy_info:
  role_name: gateway
  author: rc
  description: Deploys Kubernetes Gateway API resources including namespace, ReferenceGrant, and public Gateway.
  license: MIT
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - kubernetes
    - k3s
    - gateway-api
    - networking
    - ingress

dependencies: []
