[project]
name = "k3s-homelab"
description = "Proyecto de homelab con K3s y Ansible"
version = "0.1.0"

dependencies = [
  "docsible>=0.7.17",
  "molecule>=24.0.0",
  "molecule-plugins[vagrant]>=23.5.0",
  "python-vagrant>=1.0.0",
  "pytest-testinfra>=10.0.0",
]

requires-python = ">=3.12"

[tool.setuptools]
packages = []
py-modules = []
