---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: miners-quota
  namespace: miners
spec:
  hard:
    pods: "10"
    requests.cpu: "24000m"
    limits.cpu: "24000m"
    requests.memory: "16Gi"
    limits.memory: "16Gi"
    requests.hugepages-2Mi: "6144Mi"
    limits.hugepages-2Mi: "6144Mi"
