argument_specs:
  main:
    short_description: Installs and configures Tailscale VPN.
    description: |
      Installs Tailscale, connects to the tailnet using an auth key, and configures
      settings like DNS acceptance and SSH access.
    author: rc
    options:
      tailscale_authkey:
        type: str
        required: true
        description: Tailscale authentication key (tskey-auth-...).
