galaxy_info:
  role_name: tailscale
  author: Roura
  description: Installs and configures Tailscale VPN client.
  company: Personal
  license: MIT
  min_ansible_version: "2.20.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - k3s
    - kubernetes
    - vpn
    - networking
    - security
    - homelab
dependencies: []
