---
galaxy_info:
  role_name: tailscale
  author: rc
  description: Installs and configures Tailscale VPN client.
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  
  galaxy_tags:
    - k3s
    - kubernetes
    - vpn
    - networking
    - security
    - homelab

dependencies: []