apiVersion: v1
kind: ConfigMap
metadata:
  name: mining-pools
  namespace: miners
data:
  KRYPTEX_XEL_HOST: xel-us.kryptex.network
  KRYPTEX_XEL_PORT: "7019"
  KRYPTEX_XEL_SCHEME: stratum+tcp
  UNMINEABLE_AUTOLYKOS_HOST: autolykos.unmineable.com
  UNMINEABLE_AUTOLYKOS_PORT: "3333"
  UNMINEABLE_AUTOLYKOS_SCHEME: stratum+ssl
  UNMINEABLE_XELISHASH_HOST: xelishash.unmineable.com
  UNMINEABLE_XELISHASH_PORT: "3333"
  UNMINEABLE_XELISHASH_SCHEME: stratum+ssl
