apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicehash
  namespace: miners
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nicehash
  template:
    metadata:
      labels:
        app: nicehash
    spec:
      runtimeClassName: nvidia
      containers:
        - name: nicehash
          image: dockerhubnh/nicehash:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MINING_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: nicehash-secret
                  key: MINING_ADDRESS
            - name: MINING_WORKER_NAME
              valueFrom:
                configMapKeyRef:
                  name: nicehash-config
                  key: MINING_WORKER_NAME
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          resources:
            limits:
              nvidia.com/gpu: "1"
