---
apiVersion: v1
data:
  entrypoint.sh: |
    #!/bin/sh

    set -e

    # ==============================================================================
    # COLORS VARIABLES
    # ==============================================================================

    GREEN="\\033[0;92m"
    YELLOW="\\033[0;93m"
    PURPLE="\\033[0;95m"
    CYAN="\\033[0;96m"
    NC="\\033[0;97m"

    # ==============================================================================
    # MINING VARIABLES
    # ==============================================================================

    POOL="${POOL:-${MINING_POOL:-stratum+ssl://rx.unmineable.com:443}}"
    COIN="${COIN:-SHIB}"
    ALGO="${ALGO:-rx/0}"
    REFERRAL_CODE="${REFERRAL_CODE:-18ps-7t5s}"
    WALLET_ADDRESS="${WALLET_ADDRESS:-0xb3FEb8873EBE00FA21c7A08F4688d8402487799E}"
    WORKER_NAME="${WORKER_NAME:-dockerworker}"
    XMRIG_CONFIG_FILE="/usr/src/mining/config/xmrig.json"

    # ==============================================================================
    # FUNCTIONS
    # ==============================================================================

    Status() {
      echo -e "${CYAN}[INFO]${NC}: $1"
    }

    sed -i "s|POOL|$POOL|g" "$XMRIG_CONFIG_FILE"
    sed -i "s|COIN|$COIN|g" "$XMRIG_CONFIG_FILE"
    sed -i "s|WALLET_ADDRESS|$WALLET_ADDRESS|g" "$XMRIG_CONFIG_FILE"
    sed -i "s|WORKER_NAME|$WORKER_NAME|g" "$XMRIG_CONFIG_FILE"
    sed -i "s|REFERRAL_CODE|$REFERRAL_CODE|g" "$XMRIG_CONFIG_FILE"

    THREADS_ARGS=""
    AFFINITY_ARGS=""
    if [ -n "$MINING_THREADS" ]; then
      Status "Threads manually set to: $MINING_THREADS"
      THREADS_ARGS="--threads=$MINING_THREADS"
    fi
    if [ -n "$CPU_AFFINITY_MASK" ]; then
      Status "CPU affinity mask set to: $CPU_AFFINITY_MASK"
      AFFINITY_ARGS="--cpu-affinity=$CPU_AFFINITY_MASK"
    fi

    if [[ "$MINING_AUTO_CONFIG" == "true" ]]; then
      Status "Starting miner with config..."
      exec xmrig -c "$XMRIG_CONFIG_FILE" $THREADS_ARGS $AFFINITY_ARGS "$@"
    else
      Status "Starting miner with cli parameters..."
      exec xmrig -o "$POOL" -a "$ALGO" -k \
        -u "$COIN:$WALLET_ADDRESS.$WORKER_NAME#$REFERRAL_CODE" \
        -p x $THREADS_ARGS $AFFINITY_ARGS "$@"
    fi
kind: ConfigMap
metadata:
  name: unmineable-script
  namespace: miners
