apiVersion: v1
kind: ConfigMap
metadata:
  name: unmineable-config
  namespace: miners
data:
  POOL: "rx.unmineable.com:3333"
  COIN: "BNB"
  REFERRAL_CODE: "18ps-7t5s"
  WORKER_NAME: "home-miner"
  MINING_THREADS: "12"
