---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeygain
  namespace: miners
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: honeygain
  template:
    metadata:
      labels:
        app: honeygain
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: "miner.network"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: miner.network
                    operator: In
                    values: ["true"]
      containers:
        - name: honeygain
          image: honeygain/honeygain:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              honeygain -tou-accept \
                -email "$(cat /etc/honeygain/config/HONEYGAIN_EMAIL)" \
                -pass "$(cat /etc/honeygain/secret/HONEYGAIN_PASS)" \
                -device "$(cat /etc/honeygain/config/HONEYGAIN_DEVICE)"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/honeygain/config
              readOnly: true
            - name: secret-volume
              mountPath: /etc/honeygain/secret
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: honeygain-config
        - name: secret-volume
          secret:
            secretName: honeygain-secret
