---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: honeygain-config
    envs:
      - config.env

secretGenerator:
  - name: honeygain-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
