---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unmineable-tnn-config
  namespace: miners
data:
  POOL: stratum+ssl://xelishash.unmineable.com:443
  ALGO: xelihashv3
  COIN: XEL
  REFERRAL_CODE: 18ps-7t5s
  WORKER_NAME: home-miner
  MINING_THREADS: "12"
  CPU_AFFINITY_MASK: "0x0FFF0000"
