apiVersion: v1
kind: ConfigMap
metadata:
  name: unmineable-tnn-config
  namespace: miners
data:
  ALGO: xelishashv3
  COIN: AVAX
  REFERRAL_CODE: 18ps-7t5s
  WORKER_NAME: home-miner
  MINING_THREADS: "12"
  CPU_AFFINITY_MASK: "0x0FFF0000"
  DEV_FEE: "1.0"
