---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unmineable-tnn
  namespace: miners
  labels:
    app: unmineable-tnn
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unmineable-tnn
  template:
    metadata:
      labels:
        app: unmineable-tnn
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: unmineable-tnn
          image: roucru/k3s-cpu-miner:tnn
          imagePullPolicy: Always
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: POOL
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: POOL
            - name: ALGO
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: ALGO
            - name: COIN
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: COIN
            - name: REFERRAL_CODE
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: REFERRAL_CODE
            - name: WORKER_NAME
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: WORKER_NAME
            - name: MINING_THREADS
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: MINING_THREADS
            - name: CPU_AFFINITY_MASK
              valueFrom:
                configMapKeyRef:
                  name: unmineable-tnn-config
                  key: CPU_AFFINITY_MASK
            - name: WALLET_ADDRESS
              value: "xel:9je8c3lfsl4nrjl7z6xc59jks88vk9mng5yayzxu87q79m9cwgtqqd4e2ty"
          resources:
            requests:
              cpu: "12"
              memory: 3Gi
              hugepages-2Mi: 2560Mi
            limits:
              cpu: "12"
              memory: 3Gi
              hugepages-2Mi: 2560Mi
          volumeMounts:
            - name: dev-cpu
              mountPath: /dev/cpu
            - name: hugepages
              mountPath: /dev/hugepages
      volumes:
        - name: dev-cpu
          hostPath:
            path: /dev/cpu
            type: Directory
        - name: hugepages
          emptyDir:
            medium: HugePages-2Mi
