apiVersion: v1
kind: ConfigMap
metadata:
  name: unmineable-gpu-rigel-config
  namespace: miners
data:
  MINING_ALGO: xelishashv3
  MINING_COIN: XEL
  MINING_PASS: x
  MINING_PORT: "7019"
  MINING_WORKER_NAME: k8s-gpu
  REFERRAL_CODE: 18ps-7t5s
  GPU_CORE_OFFSET: "0"
  GPU_MEM_OFFSET: "0"
  GPU_TEMP_CORE_MIN: "55"
  GPU_TEMP_CORE_MAX: "80"
  GPU_TEMP_MEM_MIN: "70"
  GPU_TEMP_MEM_MAX: "85"