---
galaxy_info:
  role_name: k3s_server
  author: rc
  description: Instala y configura K3s Kubernetes server para homelab
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  
  galaxy_tags:
    - k3s
    - kubernetes
    - k8s
    - container
    - orchestration
    - homelab

dependencies: []