---
galaxy_info:
  role_name: k3s_server
  author: Roura
  description: Installs and configures K3s Kubernetes server for homelab usage.
  company: Personal
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - k3s
    - kubernetes
    - k8s
    - container
    - orchestration
    - homelab
dependencies: []
