---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unmineable-gpu-config
  namespace: miners
data:
  MINING_WORKER_NAME: "k8s-gpu"
  MINING_POOL: "autolykos.unmineable.com"
  MINING_PORT: "3333"
  MINING_ALGO: "AUTOLYKOS2"
  MINING_COIN: "BNB"
  MINING_PASS: "x"
  MINING_TLS: "off"
  REFERRAL_CODE: "18ps-7t5s"
