---
namespace: miners
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configMapGenerator:
  - name: unmineable-gpu-entrypoint
    files:
      - entrypoint.sh
  - name: unmineable-gpu-config
    envs:
      - miner.env

secretGenerator:
  - name: unmineable-gpu-secret
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
