apiVersion: v1
kind: ConfigMap
metadata:
  name: nicehash-config
  namespace: miners
data:
  MINING_WORKER_NAME: "k8s-server"
  MINING_POOL: "beamv3.auto.nicehash.com"
  MINING_PORT: "3387"
  MINING_ALGO: "BEAM-III"
  MINING_PASS: "x"
  MINING_TLS: "off"
