#   al               bash             clojure          cpp              csharp           csharp_omnisharp
#   dart             elixir           elm              erlang           fortran          go
#   haskell          java             julia            kotlin           lua              markdown
#   nix              perl             php              python           python_jedi      r
#   rego             ruby             ruby_solargraph  rust             scala            swift
#   terraform        typescript       typescript_vts   yaml             zig
languages:
  - bash
  - yaml
  - markdown
encoding: "utf-8"
ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false
excluded_tools: []
initial_prompt: ""
project_name: "k3s-homelab"
included_optional_tools: []
