# Installation of gVisor (runsc)
# @docsible Download gVisor runtime binary
- name: Install runsc binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/gvisor/releases/release/{{ gvisor_version }}/x86_64/runsc"
    dest: /usr/local/bin/runsc
    mode: '0750'
    owner: root
    group: root
    checksum: "sha512:https://storage.googleapis.com/gvisor/releases/release/{{ gvisor_version }}/x86_64/runsc.sha512"
  when: "'k3s_server' in group_names and (gvisor_install | default(true) | bool)"
