# Title: gVisor Install
# Description: Enable gVisor installation and RuntimeClass deployment.
# Type: bool
# Required: false
gvisor_install: true

# Title: gVisor Version
# Description: Version of gVisor runtime to install.
# Type: str
# Required: false
gvisor_version: "20231204.0"
